{
"global_params":{
}
,
"user_header":{
"audio_ext":".wav",
"author":"D002662",
"comment":"",
"language":"en-US",
"mastery_score_percent":"80",
"max_score_percent":"100",
"shelftype":"standard",
"title":"Creating Customer Invoices",
"version":"10.4.4"}
,
"tourstops":[
{
"index":0,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_9C7B31295EF14F5A8849AC2F73E112EE",
"jumpable":false,
"visible":true,
"callable":false,
"duration":9,
"audio_duration":0,
"macros":[
{
"macro_template":"start_unit",
"time":0,
"duration":10,
"uid":"MAC_27574E604D3564A1",
"possible_points":42,
"mastery_score":34,
"task_text":"",
"task_width":240,
"task_height":0,
"task_orientation":"NE",
"task_bgcolor":"#ffffb7",
"in_practice":false,
"in_test":true,
"config_templates":"<CTRoot>\n<CTFile name=\"Standard\">\n<ConfigurationTemplate>\r\n    <CTHeader webcompat=\"0\" proc_error_correction=\"0\" xRayProject=\"0\" revision=\"$Id: header.xml,v 1.14 2011-03-10 16:50:56 stefanh Exp $\" text_recognition_mode=\"3\" text_recognition_methods=\"\" profile_language=\"eng\">\r\n        <Header threshold=\"0.800000\">\r\n            <PageID>\r\n                <Attributes>\r\n                    <MSAA value=\"act_tabs,act_treeitem,desc,page_id,state,text,type,value\"\/>\r\n                    <WINDOWS value=\"class,text\"\/>\r\n                <\/Attributes>\r\n            <\/PageID>\r\n            <ContextID object_attribute=\"\" context_attribute_name=\"\" rule=\"0\"\/>\r\n            <Ident classname=\"\" exename=\"\" urls=\"\" version=\"\" caption=\"\"\/>\r\n        <\/Header>\r\n        <Global min_w=\"-1\" min_h=\"-1\" max_w=\"-1\" max_h=\"-1\">\r\n            <SAP recursion_level=\"3\" has_context_info=\"0\" find_embedded=\"0\" access_check=\"0\"\/>\r\n            <JAVA use_jab_watcher=\"1\" jab_tab_lookuplevel=\"3\" jab_tree_lookuplevel=\"3\" enable_jab_button_handler=\"1\" jab_rerecognition_use_name=\"1\" max_sl_edit_jab_height=\"0\" init_with_setpage=\"0\" jab_generate_path=\"1\" java_rere_use_empty_name=\"1\" java_use_fast_path=\"1\" access_check=\"0\"\/>\r\n            <MSAA generate_path=\"1\" max_name_objs=\"0\" msaa_tab_lookuplevel=\"3\" msaa_tree_lookuplevel=\"3\" rerecognition_use_names=\"0\"\/>\r\n            <UIAutomation uia_tab_lookuplevel=\"3\" uia_tree_lookuplevel=\"3\" unique_ids=\"0\" rerecognition_use_names=\"0\" uia_generate_path=\"1\" max_name_objs=\"0\"\/>\r\n            <UIACOM caching=\"0\" generate_path=\"1\" max_name_objs=\"200\"\/>\r\n            <HTML handle_zoom=\"1\" has_context_info=\"0\" batch_rerecognition=\"0\" pgkey_fback=\"0\" set_attrb=\"0\" capture_multiple_dlg=\"0\" ignore_dynamic_ids=\"1\">\r\n                <GlobalScript><\/GlobalScript>\r\n            <\/HTML>\r\n            <HTML3 handle_zoom=\"1\" has_context_info=\"0\" batch_rerecognition=\"0\" capture_multiple_dlg=\"0\" rlevel=\"0\" ignore_dynamic_ids=\"1\" is_xray_profile=\"0\">\r\n                <GlobalScript><\/GlobalScript>\r\n            <\/HTML3>\r\n            <DIG generate_path=\"0\" generate_triangle=\"1\">\r\n                <Settings>\r\n                    <CParams min_object_height=\"8\" min_object_width=\"8\">\r\n                        <ClusterParams epsh=\"4\" epsv=\"6\" min_pts=\"2\" max_cl_size=\"20\"\/>\r\n                        <ClusterParams epsh=\"15\" epsv=\"1\" min_pts=\"1\" max_cl_size=\"20\"\/>\r\n                        <ClusterParams epsh=\"10\" epsv=\"1\" min_pts=\"10\" max_cl_size=\"20\"\/>\r\n                        <ClusterParams epsh=\"10\" epsv=\"1\" min_pts=\"11\" max_cl_size=\"16\"\/>\r\n                    <\/CParams>\r\n                    <RParams max_gap=\"1\" min_line_length=\"10\" threshold=\"30\"\/>\r\n                    <CiParams circle_threshold=\"0.800000\" inner_threshold=\"0.950000\" outer_threshold=\"0.950000\">\r\n                        <RadiusRange min=\"6\" max=\"7\"\/>\r\n                    <\/CiParams>\r\n                <\/Settings>\r\n                <PointAnalyzing all=\"0\" analyze_width=\"50\" analyze_height=\"250\" merge_cross_objects=\"1\"\/>\r\n                <Contexts>\r\n                    <Context type=\"menubar\" max_hor_inter_obj_dist=\"30\" max_vert_inter_obj_dist=\"10\" top_min_dist=\"15\" top_max_dist=\"70\">\r\n                        <ObjectSize>\r\n                            <WidthRange min=\"9\" max=\"300\"\/>\r\n                            <HeightRange min=\"8\" max=\"25\"\/>\r\n                        <\/ObjectSize>\r\n                        <Alignment type=\"center\" direction=\"horizontal\" maxdiff=\"3\"\/>\r\n                        <Alignment type=\"left\" direction=\"vertical\" maxdiff=\"1\"\/>\r\n                    <\/Context>\r\n                <\/Contexts>\r\n            <\/DIG>\r\n            <SAPB1 generate_path=\"1\" analyze_point_timeout=\"3000\" get_pagekey_timeout=\"7000\"\/>\r\n            <GRAPHIC>\r\n                <SupportedDesigns\/>\r\n                <FontTemplateFiles>\r\n                    <FontTemplateFile file=\"glyphs_latin_MS_Sans_Serif_size8_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_MS_Sans_Serif_size9_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Tahoma_size8_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Tahoma_size9_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Arial_size9_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Arial_size8_incl_underlines.xml\"\/>\r\n                <\/FontTemplateFiles>\r\n            <\/GRAPHIC>\r\n        <\/Global>\r\n    <\/CTHeader>\r\n<\/ConfigurationTemplate><\/CTFile>\n<\/CTRoot>\n"}
]
}
,{
"index":1,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_E96CEF1B58B84EA1AB3EE53832DA2113",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_5B1AA788BA66B9A7",
"new_step":"Home",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_DE0C928ADF0489B6",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>Would you like to know more about how a billing clerk creates a customer invoice?<\/p>\n<p>&nbsp;<\/p>\n<p>If so, follow this interactive tutorial.<\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":572,
"b_height_p":174,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.668681"}
,
"DocXY":{
"x":"0.499977",
"y":"0.668681"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":2,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_44B807D28F0B408D99D118BFC6DB053B",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_61CF2D9E04F6FB8A",
"new_step":"Home",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_C4FD505BD7A2BA9D",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span><span style=\"font-weight:normal; \">.<\/span><\/p>\n",
"explanation_p":"<p>To open the app, select the <span style=\"font-style:italic; \">Create Billing Documents <\/span>tile.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_2.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":252,
"b_height_p":70,
"orientation_p":"ES",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.149096",
"y":"0.345846"}
,
"DocXY":{
"x":"0.149096",
"y":"0.345846"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":332,
"top":198}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":60,
"top":200,
"width":170,
"height":170}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":3,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_30C992B29CFF4EAC97FA20290FB302AA",
"jumpable":true,
"visible":true,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_AD469A825D527D8D",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_FDC0637306F201A8",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":25,
"top":114,
"width":1524,
"height":108}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_3EC1B09AA9F1B797",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>In this section of the screen, you can filter for your delivery-related billing due items.<\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":460,
"b_height_p":70,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.547326"}
,
"DocXY":{
"x":"0.499977",
"y":"0.547326"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":4,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_401C65AAEF764267B1EA6B09FC6D87F4",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_1FB6412F52F8FABC",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_899906924468EF97",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>To filter for your delivery, in the <span style=\"font-style:italic; \">SD Document<\/span>&nbsp;field, enter <span style=\"font-weight:bold; \">210000003<\/span> and press Enter.<\/p>\n",
"text_d":"210000003",
"regexp":"\/.{5}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":283,
"b_height_p":107,
"orientation_p":"SE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.073289",
"y":"0.268193"}
,
"DocXY":{
"x":"0.073289",
"y":"0.268193"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":37,
"top":191,
"width":160,
"height":20}
,
"ctl_rect":{
"left":37,
"top":191,
"width":160,
"height":20}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":5,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_0A5D9FFE57224C579488118EE58A0CCC",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_DE3B7B6326E45C96",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_8E82010583FED4A1",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Open the <span style=\"font-style:italic; \">SD Document Category<\/span> list.<\/p>\n",
"action":"lclick",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":230,
"b_height_p":94,
"orientation_p":"S",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.261891",
"y":"0.265751"}
,
"DocXY":{
"x":"0.261891",
"y":"0.265751"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":-1,
"top":-1}
,
"click_count":1,
"ctl_rect":{
"left":404,
"top":191,
"width":27,
"height":20}
,
"cursor_hand":true}
]
}
,{
"index":6,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_2527833D84B34EEA929C06482DB3F244",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_CC94724223E0DE9A",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_70E54CAE8EE2F2B0",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Select <span style=\"font-style:italic; \">Delivery<\/span>.<\/p>\n",
"action":"lclick",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":90,
"orientation_p":"W",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.156634",
"y":"0.434455"}
,
"DocXY":{
"x":"0.156634",
"y":"0.434455"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":-1,
"top":-1}
,
"click_count":1,
"ctl_rect":{
"left":259,
"top":352,
"width":11,
"height":11}
,
"cursor_hand":true}
]
}
,{
"index":7,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_36ACEF9FE1CA493383F4F7B01348D67E",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_58124F12DCD801A9",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_9C9867077637ABA9",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Sold-To-Party<\/span> field, enter <span style=\"font-weight:bold; \">10100003<\/span> and press Enter.<\/p>\n",
"text_d":"10100003",
"regexp":"\/.{5}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":289,
"b_height_p":88,
"orientation_p":"S",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.333959",
"y":"0.265751"}
,
"DocXY":{
"x":"0.333959",
"y":"0.265751"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":453,
"top":191,
"width":160,
"height":20}
,
"ctl_rect":{
"left":453,
"top":191,
"width":160,
"height":20}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":8,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_E63E9103963445218E400DBFA0EAC72F",
"jumpable":true,
"visible":true,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_988A7D2DEB6A8193",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_5DBB7005D934CEBF",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":36,
"top":316,
"width":1511,
"height":32}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_8CDB8D96994BFF9F",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>Your delivery-related billing due list item appears.<\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":386,
"b_height_p":70,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.548516"}
,
"DocXY":{
"x":"0.499977",
"y":"0.548516"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":9,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_471EDE54479F4A4A91A0E4B959C64519",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_9DDBCA4A279320A2",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_CDA87969BE5403BE",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">Billing Settings<\/span>.<\/p>\n",
"action":"lclick",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":233,
"b_height_p":70,
"orientation_p":"TL",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.963012",
"y":"0.947799"}
,
"DocXY":{
"x":"0.963012",
"y":"0.947799"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":-1,
"top":-1}
,
"click_count":1,
"ctl_rect":{
"left":1518,
"top":789,
"width":39,
"height":29}
,
"cursor_hand":true}
]
}
,{
"index":10,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_25DEEDF5FFDD4857A00B1E032D31D7C0",
"jumpable":true,
"visible":true,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_2D6C7FABC134919A",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_E5944ADAEA3F69BE",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":400,
"top":429,
"width":792,
"height":62}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_FD760CCA04B48ABA",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>Check that the <span style=\"font-style:italic; \">Automatically post billing documents<\/span> and the <span style=\"font-style:italic; \">Display billing documents after creation<\/span> settings are set to <span style=\"font-style:italic; \">On<\/span>. <\/p>\n<p>&nbsp;<\/p>\n<p>For this tutorial, the settings have already been selected for you.<\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":516,
"b_height_p":70,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.535714",
"y":"0.765759"}
,
"DocXY":{
"x":"0.535714",
"y":"0.765759"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":11,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_082E9144C85B4C439AFBA0E76C4CE7E4",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_631B042B7154F6AA",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_162F2AECEC216D90",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">OK<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_8.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.737469",
"y":"0.645609"}
,
"DocXY":{
"x":"0.737469",
"y":"0.645609"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1173,
"top":513}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1160,
"top":501,
"width":32,
"height":23}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":12,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_73E3D2C31E68451294DB5869FB6AF8CE",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_68B4FC7053BC5994",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_6D3C45812EAD4280",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Select <span style=\"font-style:italic; \">210000003<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_9.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":222,
"b_height_p":70,
"orientation_p":"BR",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.031327",
"y":"0.421088"}
,
"DocXY":{
"x":"0.031327",
"y":"0.421088"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":51,
"top":334}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":42,
"top":324,
"width":15,
"height":17}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":13,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_A49395A13F3B491894B6AC6BE1F4519E",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_601957208BC357AC",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_998F3755BB23D7BB",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>To create the billing document for the selected item, choose <span style=\"font-style:italic; \">Create<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":336,
"b_height_p":70,
"orientation_p":"NW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.929183",
"y":"0.951446"}
,
"DocXY":{
"x":"0.929183",
"y":"0.951446"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1482,
"top":801}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1453,
"top":791,
"width":59,
"height":27}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":14,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_A3DD9476091A4CBE8241CC8AE6679F7F",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_F5443CB6D9B36680",
"new_step":"Create Billing Documents",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_374CB528FDB8CEAC",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">OK<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_17.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"S",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.551354",
"y":"0.655314"}
,
"DocXY":{
"x":"0.551354",
"y":"0.655314"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":880,
"top":520}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":863,
"top":509,
"width":31,
"height":22}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":15,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_06D9755724D74F8891FDCEAF9E9D0881",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_C3424D9155C25F94",
"new_step":"Billing Document",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_938EDA320F092180",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>The system generates a customer invoice and displays the invoice details.<\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":434,
"b_height_p":70,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.425437",
"y":"0.529122"}
,
"DocXY":{
"x":"0.425437",
"y":"0.529122"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":16,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_16FCCCB88A0F499C8A0FDA33B723E9CA",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_14A7CF7DD54B6BB6",
"new_step":"Billing Document",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_273EA4D488B278A6",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">Save<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.939849",
"y":"0.950225"}
,
"DocXY":{
"x":"0.939849",
"y":"0.950225"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1494,
"top":808}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1475,
"top":791,
"width":49,
"height":27}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":17,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_339D9E842ADE40569455F5C5A9356E45",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_3EF9678B06FD95AC",
"new_step":"Billing Document",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_366807809E138BA1",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>To display a preview of the invoice document in PDF form, choose <span style=\"font-style:italic; \">Preview<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_23.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":302,
"b_height_p":70,
"orientation_p":"N",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.739956",
"y":"0.952667"}
,
"DocXY":{
"x":"0.739956",
"y":"0.952667"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1181,
"top":802}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1148,
"top":792,
"width":65,
"height":23}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":18,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_109DB15058D54F3090728E1C77E3A315",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_D746E403C4CC2DA3",
"new_step":"https:\/\/hc6-715.wdf.sap.corp\/sap\/opu\/odata\/SAP\/CA_OC_OUTPUT_REQUEST_SRV\/Roots(ApplObjectType='BILLING_DOCUMENT',ApplObjectId='0090002724')\/Preview\/$value\/",
"dump_page":"dump_page1",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_E1E7C9F2B646DA99",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>A preview of the invoice document in PDF form appears in a new window.<\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":426,
"b_height_p":76,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.593332",
"y":"0.223301"}
,
"DocXY":{
"x":"0.593332",
"y":"0.223301"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":19,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_1559120E86B0415F877DE8DE026BE471",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_232BEEB9ABA778B3",
"new_step":"https:\/\/hc6-715.wdf.sap.corp\/sap\/opu\/odata\/SAP\/CA_OC_OUTPUT_REQUEST_SRV\/Roots(ApplObjectType='BILLING_DOCUMENT',ApplObjectId='0090002724')\/Preview\/$value\/",
"dump_page":"dump_page1",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_CF99FBB260434C9A",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">Close<\/span>.<\/p>\n",
"action":"lclick",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"BL",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.984955",
"y":"0.038819"}
,
"DocXY":{
"x":"0.984955",
"y":"0.038819"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":-1,
"top":-1}
,
"click_count":1,
"ctl_rect":{
"left":1553,
"top":5,
"width":38,
"height":22}
,
"cursor_hand":true}
]
}
,{
"index":20,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_EEB856C44EE4440BAC446A12FAC27E69",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_72368CEA1C071AAA",
"new_step":"Billing Document",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_AD759845B92C739E",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span><span style=\"font-weight:normal; \">.<\/span><\/p>\n",
"explanation_p":"<p>To return to the launchpad, choose <span style=\"font-style:italic; \">Home<\/span><span style=\"font-style:normal; \">.<\/span><\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_11.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":253,
"b_height_p":70,
"orientation_p":"ES",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.114031",
"y":"0.065507"}
,
"DocXY":{
"x":"0.114031",
"y":"0.065507"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":161,
"top":55}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":145,
"top":41,
"width":30,
"height":24}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":21,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_D5254C6DF8FF4503B2CEF03CD3D7879B",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_386BCA920BFAAE88",
"new_step":"Home",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_5D8A03CECF72E7BD",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>You have successfully created a customer invoice.<\/p>\n<p>&nbsp;<\/p>\n<p>This concludes the interactive tutorial.<\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":498,
"b_height_p":162,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.612848"}
,
"DocXY":{
"x":"0.499977",
"y":"0.612848"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":22,
"title":"Creating Customer Invoices",
"audio":"",
"uid":"TS_2C7CD11F0F874750BC85ED92E7C12230",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_slide",
"time":0,
"duration":10,
"uid":"MAC_12A11B2357211F8C",
"src":"slide!SL_7257A6FB1A19D6A0:",
"page_duration":-1,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":false,
"in_guided":false,
"in_pres":false,
"doc_enable":false,
"process_enable":false,
"doc_heading":false}
,{
"macro_template":"end_unit",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_9AB63412F143BBB6"}
]
}
]
}
