{
"global_params":{
}
,
"user_header":{
"audio_ext":".wav",
"author":"D002662",
"comment":"",
"language":"en-US",
"mastery_score_percent":"80",
"max_score_percent":"100",
"shelftype":"standard",
"title":"Creating Purchase Requisitions ",
"version":"10.4.4"}
,
"tourstops":[
{
"index":0,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_9C7B31295EF14F5A8849AC2F73E112EE",
"jumpable":true,
"visible":true,
"callable":false,
"duration":9,
"audio_duration":0,
"macros":[
{
"macro_template":"start_unit",
"time":0,
"duration":10,
"uid":"MAC_27574E604D3564A1",
"possible_points":54,
"mastery_score":44,
"task_text":"",
"task_width":240,
"task_height":0,
"task_orientation":"NE",
"task_bgcolor":"#ffffb7",
"in_practice":false,
"in_test":true,
"config_templates":"<CTRoot><CTFile name=\"Standard\"><ConfigurationTemplate>\r\n    <CTHeader webcompat=\"0\" proc_error_correction=\"0\" revision=\"$Id: header.xml,v 1.14 2011-03-10 16:50:56 stefanh Exp $\" text_recognition_mode=\"3\" text_recognition_methods=\"\" profile_language=\"eng\">\r\n        <Header threshold=\"0.800000\">\r\n            <PageID>\r\n                <Attributes>\r\n                    <MSAA value=\"act_tabs,act_treeitem,desc,page_id,state,text,type,value\"\/>\r\n                    <WINDOWS value=\"class,text\"\/>\r\n                <\/Attributes>\r\n            <\/PageID>\r\n            <ContextID object_attribute=\"\" context_attribute_name=\"\" rule=\"0\"\/>\r\n            <Ident classname=\"\" exename=\"\" urls=\"\" version=\"\" caption=\"\"\/>\r\n        <\/Header>\r\n        <Global min_w=\"-1\" min_h=\"-1\" max_w=\"-1\" max_h=\"-1\">\r\n            <SAP recursion_level=\"3\" has_context_info=\"0\" find_embedded=\"0\" access_check=\"0\"\/>\r\n            <JAVA use_jab_watcher=\"1\" jab_tab_lookuplevel=\"3\" jab_tree_lookuplevel=\"3\" enable_jab_button_handler=\"1\" jab_rerecognition_use_name=\"1\" max_sl_edit_jab_height=\"0\" init_with_setpage=\"0\" jab_generate_path=\"1\" java_rere_use_empty_name=\"1\" java_use_fast_path=\"1\" access_check=\"0\"\/>\r\n            <MSAA generate_path=\"1\" max_name_objs=\"0\" msaa_tab_lookuplevel=\"3\" msaa_tree_lookuplevel=\"3\" rerecognition_use_names=\"0\"\/>\r\n            <UIAutomation uia_tab_lookuplevel=\"3\" uia_tree_lookuplevel=\"3\" unique_ids=\"0\" rerecognition_use_names=\"0\" uia_generate_path=\"1\" max_name_objs=\"0\"\/>\r\n            <UIACOM caching=\"0\" generate_path=\"1\" max_name_objs=\"200\"\/>\r\n            <HTML handle_zoom=\"1\" has_context_info=\"0\" batch_rerecognition=\"0\" pgkey_fback=\"0\" set_attrb=\"0\" capture_multiple_dlg=\"0\" ignore_dynamic_ids=\"1\">\r\n                <GlobalScript\/>\r\n            <\/HTML>\r\n            <HTML3 handle_zoom=\"1\" has_context_info=\"0\" batch_rerecognition=\"0\" capture_multiple_dlg=\"0\" rlevel=\"0\" ignore_dynamic_ids=\"1\" is_xray_profile=\"0\">\r\n                <GlobalScript\/>\r\n            <\/HTML3>\r\n            <DIG generate_path=\"0\">\r\n                <Settings>\r\n                    <CParams min_object_height=\"8\" min_object_width=\"8\">\r\n                        <ClusterParams epsh=\"4\" epsv=\"6\" min_pts=\"2\" max_cl_size=\"20\"\/>\r\n                        <ClusterParams epsh=\"15\" epsv=\"1\" min_pts=\"1\" max_cl_size=\"20\"\/>\r\n                        <ClusterParams epsh=\"10\" epsv=\"1\" min_pts=\"10\" max_cl_size=\"20\"\/>\r\n                        <ClusterParams epsh=\"10\" epsv=\"1\" min_pts=\"11\" max_cl_size=\"16\"\/>\r\n                    <\/CParams>\r\n                    <RParams max_gap=\"1\" min_line_length=\"10\" threshold=\"30\"\/>\r\n                    <CiParams circle_threshold=\"0.800000\" inner_threshold=\"0.950000\" outer_threshold=\"0.950000\">\r\n                        <RadiusRange min=\"6\" max=\"7\"\/>\r\n                    <\/CiParams>\r\n                <\/Settings>\r\n                <PointAnalyzing all=\"0\" analyze_width=\"50\" analyze_height=\"250\" merge_cross_objects=\"1\"\/>\r\n                <Contexts>\r\n                    <Context type=\"menubar\" max_hor_inter_obj_dist=\"30\" max_vert_inter_obj_dist=\"10\" top_min_dist=\"15\" top_max_dist=\"70\">\r\n                        <ObjectSize>\r\n                            <WidthRange min=\"9\" max=\"300\"\/>\r\n                            <HeightRange min=\"8\" max=\"25\"\/>\r\n                        <\/ObjectSize>\r\n                        <Alignment type=\"center\" direction=\"horizontal\" maxdiff=\"3\"\/>\r\n                        <Alignment type=\"left\" direction=\"vertical\" maxdiff=\"1\"\/>\r\n                    <\/Context>\r\n                <\/Contexts>\r\n            <\/DIG>\r\n            <SAPB1 generate_path=\"1\" analyze_point_timeout=\"3000\" get_pagekey_timeout=\"7000\"\/>\r\n            <GRAPHIC>\r\n                <SupportedDesigns\/>\r\n                <FontTemplateFiles>\r\n                    <FontTemplateFile file=\"glyphs_latin_MS_Sans_Serif_size8_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_MS_Sans_Serif_size9_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Tahoma_size8_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Tahoma_size9_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Arial_size9_incl_underlines.xml\"\/>\r\n                    <FontTemplateFile file=\"glyphs_latin_Arial_size8_incl_underlines.xml\"\/>\r\n                <\/FontTemplateFiles>\r\n            <\/GRAPHIC>\r\n        <\/Global>\r\n    <\/CTHeader>\r\n<\/ConfigurationTemplate><\/CTFile><CTFile name=\"SAPUI5\">1591618219<\/CTFile><\/CTRoot>"}
]
}
,{
"index":1,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_A3ED565E5F28429FB41CD96D25A38615",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_A95AB0CF2D21E08D",
"new_step":"Home - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_D5C1154EF3DCE6AA",
"all_like_demo":false,
"explanation_d":"<p>&nbsp;<\/p>\n<p>Would you like to know more about how a purchaser creates purchase requisitions? <\/p>\n<p>&nbsp;<\/p>\n<p>If so, follow this interactive tutorial. <\/p>\n<p>&nbsp;<\/p>\n<p>&nbsp;<\/p>\n",
"explanation_p":"<p>Would you like to know more about how a purchaser creates purchase requisitions? <\/p>\n<p>&nbsp;<\/p>\n<p>If so, follow this interactive&nbsp;tutorial. <\/p>\n",
"type":"info",
"bubblestyle_d":"dark_title_green",
"b_width":362,
"b_height":84,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":472,
"b_height_p":92,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.551354",
"y":"0.607996"}
,
"DocXY":{
"x":"0.551354",
"y":"0.607996"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":2,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_D34E12CA397C45759F8A1698B28C91C0",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_E8BDF46DA5E65FA8",
"new_step":"Home - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_CC755485684235BB",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>To open the app, select the <span style=\"font-style:italic; \">Create Purchase Requisition Advanced <\/span>tile. <\/p>\n",
"fieldname":"\n\nCreate Purchase Requisition\n\nAdvanced",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":323,
"b_height_p":96,
"orientation_p":"E",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.152255",
"y":"0.370123"}
,
"DocXY":{
"x":"0.152255",
"y":"0.370123"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":120,
"top":287}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":56,
"top":220,
"width":176,
"height":176}
,
"cursor_hand":true,
"ctl_button":true,
"ctl_tooltip":""}
]
}
,{
"index":3,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_A3786E10C2B54022B194B1FAD6067658",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_6B0A30FF396F1198",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_998AB8C4FF16898A",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>For this tutorial, the item is already expanded for you. <\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":418,
"b_height_p":108,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.263783",
"y":"0.480568"}
,
"DocXY":{
"x":"0.263783",
"y":"0.480568"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":4,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_1B818DA14C174FB6B50B91DD581D31B7",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_516E70495E0E3893",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_C5340759DB8A5898",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Acct. Assignment Category<\/span> field, enter <span style=\"font-weight:bold; \">A <\/span>and press Enter. <\/p>\n",
"text_d":"A",
"regexp":"\/.{1}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":326,
"b_height_p":111,
"orientation_p":"SE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.124666",
"y":"0.333715"}
,
"DocXY":{
"x":"0.124666",
"y":"0.333715"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":176,
"top":247,
"width":44,
"height":22}
,
"ctl_rect":{
"left":176,
"top":247,
"width":44,
"height":22}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":5,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_84A287B15B964F69A1738163D0E6EBDF",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_E9C92335F1B18B5",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_DEB63D2F4260F884",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Short Text<\/span> field, enter <span style=\"font-weight:bold; \">Server <\/span>and press Enter. <\/p>\n",
"text_d":"Server",
"regexp":"\/.{5}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":255,
"b_height_p":103,
"orientation_p":"S",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.296971",
"y":"0.333715"}
,
"DocXY":{
"x":"0.296971",
"y":"0.333715"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":366,
"top":247,
"width":210,
"height":22}
,
"ctl_rect":{
"left":366,
"top":247,
"width":210,
"height":22}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":6,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_C78DD7CF8564448894ACEF0938F727ED",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_58B42303EAC006B2",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_B10F80FCD53AEEA1",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Quantity <\/span>field, enter <span style=\"font-weight:bold; \">1 <\/span>and press Enter. <\/p>\n",
"text_d":"1",
"regexp":"\/.{1}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":250,
"b_height_p":106,
"orientation_p":"SE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.387213",
"y":"0.332494"}
,
"DocXY":{
"x":"0.387213",
"y":"0.332494"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":576,
"top":247,
"width":69,
"height":22}
,
"ctl_rect":{
"left":576,
"top":247,
"width":69,
"height":22}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":7,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_35D124BC59F64C4BB3E0EC78385D67A1",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_9143AE3BA917F180",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_7474BEF558EE7FB2",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Unit of Measure<\/span> field, enter <span style=\"font-weight:bold; \">PC <\/span>and press Enter.<\/p>\n",
"text_d":"PC",
"regexp":"\/.{2}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":292,
"b_height_p":114,
"orientation_p":"SE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.420417",
"y":"0.334951"}
,
"DocXY":{
"x":"0.420417",
"y":"0.334951"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":649,
"top":247,
"width":43,
"height":20}
,
"ctl_rect":{
"left":649,
"top":247,
"width":43,
"height":20}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":8,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_DF21476DCDEE4BEF92296AB773AC7973",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_9E1B8B162D209C96",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_3047332486C26791",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Mtl Group <\/span>field, enter <span style=\"font-weight:bold; \">YBFA08 <\/span>and press Enter. <\/p>\n",
"text_d":"YBFA08",
"regexp":"\/.{5}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":250,
"b_height_p":40,
"orientation_p":"SE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.550744",
"y":"0.332494"}
,
"DocXY":{
"x":"0.550744",
"y":"0.332494"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":821,
"top":248,
"width":97,
"height":21}
,
"ctl_rect":{
"left":821,
"top":248,
"width":97,
"height":21}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":9,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_BC9F4958FC294FB8AA1C5CCAC633C7C6",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_5B0ABB2A5EF37892",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_E021B58CAFBBBEA5",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the<span style=\"font-style:italic; \"> Plant <\/span>field, enter <span style=\"font-weight:bold; \">1710<\/span> and press Enter. <\/p>\n",
"text_d":"1710",
"regexp":"\/.{4}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":226,
"b_height_p":98,
"orientation_p":"S",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.609003",
"y":"0.333715"}
,
"DocXY":{
"x":"0.609003",
"y":"0.333715"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":920,
"top":245,
"width":110,
"height":23}
,
"ctl_rect":{
"left":920,
"top":245,
"width":110,
"height":23}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":10,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_A181FAD16B934EF285001251AE356553",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_6E466AE2809D5AF",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_492C24EA35793B7",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Purchase Group<\/span> field, enter <span style=\"font-weight:bold; \">001<\/span> and press Enter. <\/p>\n",
"text_d":"001",
"regexp":"\/.{3}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":277,
"b_height_p":103,
"orientation_p":"SW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.716152",
"y":"0.337377"}
,
"DocXY":{
"x":"0.716152",
"y":"0.337377"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":1121,
"top":248,
"width":42,
"height":20}
,
"ctl_rect":{
"left":1121,
"top":248,
"width":42,
"height":20}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":11,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_9A2E3D4E66DC46D39E4932FE1FC31B3E",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_BEE30F2D546EE58C",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_ED6EB2486E78BA82",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Des. Suppl<\/span> field, enter <span style=\"font-weight:bold; \">17300001<\/span> and press Enter.<\/p>\n<p>&nbsp;<\/p>\n",
"text_d":"17300001",
"regexp":"\/.{5}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":291,
"b_height_p":86,
"orientation_p":"SW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.870283",
"y":"0.336141"}
,
"DocXY":{
"x":"0.870283",
"y":"0.336141"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":1337,
"top":247,
"width":95,
"height":22}
,
"ctl_rect":{
"left":1337,
"top":247,
"width":95,
"height":22}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":12,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_3758EFBB2EDC43FEA89633A76B4AA893",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_C99EDCBAA7715C90",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_EAA43D45E7201BB5",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Select the scroll bar to scroll right. <\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"N",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.499977",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":0,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":264,
"b_height_p":40,
"orientation_p":"N",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.396597",
"y":"0.832517"}
,
"DocXY":{
"x":"0.396597",
"y":"0.832517"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":993,
"top":700}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":176,
"top":695,
"width":954,
"height":12}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":13,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_54BB9DE0747C414386D2F169E89494E4",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_4E2B20840F149DB9",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_9426AF0191460782",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">POrg <\/span>field, enter <span style=\"font-weight:bold; \">1710<\/span> and press Enter. <\/p>\n",
"text_d":"1710",
"regexp":"\/.{4}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":252,
"b_height_p":100,
"orientation_p":"SW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.716762",
"y":"0.338567"}
,
"DocXY":{
"x":"0.716762",
"y":"0.338567"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":1118,
"top":250,
"width":57,
"height":20}
,
"ctl_rect":{
"left":1118,
"top":250,
"width":57,
"height":20}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":14,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_63BAAB6600CE4F9C9001F670B0956566",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_78C6644E4B953EA7",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_71C3641FBB28BCB4",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Expand the item further. <\/p>\n",
"fieldname":"Expand Item Details Ctrl+F4 ",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.017533",
"y":"0.896834"}
,
"DocXY":{
"x":"0.017533",
"y":"0.896834"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":30,
"top":757}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":16,
"top":748,
"width":30,
"height":26}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":15,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_DA7318EDC3EF4CE2B28CCCDB278171CA",
"jumpable":true,
"visible":true,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_55D6BB06DAEAB7BE",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_294A68E947A28992",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#67a62d",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":157,
"top":558,
"width":95,
"height":32}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_35F2BF487ADA2FAC",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>For this tutorial, the quantity is already added for you. <\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":348,
"b_height_p":70,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.309499",
"y":"0.824018"}
,
"DocXY":{
"x":"0.309499",
"y":"0.824018"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":16,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_EA8DA39B9DDB436595D44837B3FEC543",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_259E624222D0E192",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_269E8DAEC34AA980",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Asset <\/span>field, enter <span style=\"font-weight:bold; \">10000022<\/span> and press Enter. <\/p>\n",
"text_d":"10000022",
"regexp":"\/.{5}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":292,
"b_height_p":104,
"orientation_p":"SW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.507500",
"y":"0.717220"}
,
"DocXY":{
"x":"0.507500",
"y":"0.717220"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":751,
"top":566,
"width":121,
"height":20}
,
"ctl_rect":{
"left":751,
"top":566,
"width":121,
"height":20}
,
"ctl_font_size":11,
"ctl_font_color":"#808080",
"ctl_bg_color":"transparent"}
]
}
,{
"index":17,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_57FA87611E8B4A2F8696CA5F92560EE1",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_4761E44BC9308BB0",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_9DA051EC583D0EBF",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">Valuation. <\/span><\/p>\n",
"fieldname":"Valuation",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":218,
"b_height_p":73,
"orientation_p":"NE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.243107",
"y":"0.509682"}
,
"DocXY":{
"x":"0.243107",
"y":"0.509682"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":380,
"top":444}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":355,
"top":427,
"width":66,
"height":32}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":18,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_AB14B9C8008F41799B27AAD385EAF728",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_A5C832D0644EA383",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_C3D5BD549491808D",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>On the <span style=\"font-style:italic; \">Valuation<\/span> tab, the following parameters are selected by default: <\/p>\n<ul>\n<li>Goods Receipt<\/li>\n<li>Inv Receipt<\/li>\n<li>GR Non-Val<\/li>\n<\/ul>\n<p>&nbsp;<\/p>\n<p>With those parameters selected, the asset is activated with the invoice receipt. If you need to activate the asset with the goods receipt,&nbsp;select the <span style=\"font-style:italic; \">Goods Receipt<\/span> and <span style=\"font-style:italic; \">Inv Receipt<\/span> checkboxes&nbsp;only.&nbsp;<\/p>\n<p>&nbsp;<\/p>\n<p>These parameters can be changed in the <span style=\"font-style:italic; \">Purchase Requisition<\/span> or <span style=\"font-style:italic; \">Purchase Order.<\/span><\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":664,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.571420",
"y":"0.430808"}
,
"DocXY":{
"x":"0.571420",
"y":"0.430808"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":19,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_A8653CB40A0B49D2B3E98D59D81467B3",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_39620664F23B738D",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_73946F95450DB892",
"explanation_d":"<p>The <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span> field is filled out.<\/p>\n",
"explanation_p":"<p>In the <span style=\"font-style:italic; \">Valuation Price <\/span>field, enter <span style=\"font-weight:bold; \">10<\/span> and press Enter. <\/p>\n",
"fieldname":"Valuation Price",
"fieldicon":"",
"ctl_init_text":"",
"text_d":"10",
"regexp":"\/.{2}\/",
"confirmation_tab":false,
"confirmation_enter":true,
"affirmation_button":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"_default",
"b_width":180,
"b_height":40,
"orientation":"NE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":304,
"b_height_p":40,
"orientation_p":"NE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.167285",
"y":"0.598276"}
,
"DocXY":{
"x":"0.167285",
"y":"0.598276"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":210,
"top":501,
"width":146,
"height":22}
,
"exec_mouse":false,
"ctl_rect":{
"left":210,
"top":501,
"width":146,
"height":22}
,
"ctl_password":false,
"is_textarea":false,
"ctl_font_family":"Sans-Serif",
"ctl_font_size":9,
"ctl_font_bold":false,
"ctl_font_italic":false,
"ctl_font_underline":false,
"ctl_font_color":"#000000",
"ctl_bg_color":"transparent"}
]
}
,{
"index":20,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_6AAEE3F69BAF42B7A8B87C901F43909E",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_DFAE1913187E5683",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_992C6FF92F8D9B9E",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">Check. <\/span><\/p>\n",
"fieldname":"Check (Ctrl+Shift+F3)",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.314519",
"y":"0.107988"}
,
"DocXY":{
"x":"0.314519",
"y":"0.107988"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":497,
"top":61}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":475,
"top":54,
"width":49,
"height":26}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":21,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_0447ECACA74C4378868659630F0756D1",
"jumpable":true,
"visible":true,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_BE4EF71C253F1499",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_E9F4C16575C5829E",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#67a62d",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":8,
"top":771,
"width":267,
"height":45}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_FB334409501E059F",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>The system confirms that no messages were issued during the check. <\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":488,
"b_height_p":72,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.288197",
"y":"0.374975"}
,
"DocXY":{
"x":"0.288197",
"y":"0.374975"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":22,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_6DA2B28D62A44129B4FBBDAD722254D1",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_B53FEE1B121FB2BA",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_B9A07E752BB76FA1",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose <span style=\"font-style:italic; \">Save. <\/span><\/p>\n",
"fieldname":"Save (Ctrl+S)",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.929183",
"y":"0.940505"}
,
"DocXY":{
"x":"0.929183",
"y":"0.940505"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1475,
"top":799}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1463,
"top":782,
"width":42,
"height":26}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":23,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_B8B441D0FB664FA5A78B486F6B0DFDFE",
"jumpable":true,
"visible":true,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_E6963510D84D80B0",
"new_step":"Create Purchase Requisition - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":"PurchaseRequisition-create:advanced"}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_7DB644058959899A",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#67a62d",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":0,
"top":772,
"width":375,
"height":50}
}
,{
"macro_template":"click",
"time":19,
"duration":10,
"uid":"MAC_D5F987C9F032D486",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>The requisition was created successfully. Record the number for future reference. <\/p>\n<p>&nbsp;<\/p>\n<p>To return to the launchpad, choose <span style=\"font-style:italic; \">SAP. <\/span><\/p>\n",
"fieldname":"Navigate to Home Page",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"SE",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"1.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":-6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"bright_title_green",
"b_width_p":378,
"b_height_p":154,
"orientation_p":"SE",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.077043",
"y":"0.060670"}
,
"DocXY":{
"x":"0.077043",
"y":"0.060670"}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":118,
"top":19}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":92,
"top":4,
"width":63,
"height":36}
,
"cursor_hand":true,
"ctl_button":true,
"ctl_tooltip":""}
]
}
,{
"index":24,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_BDC25BED5E3C42BE96378714285402B6",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_D742DC1579A82BA6",
"new_step":"Home - Internet Explorer",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_D7DE65A3D7EF90B7",
"all_like_demo":false,
"explanation_d":"",
"explanation_p":"<p>You have successfully created a purchase requisition.<\/p>\n<p>&nbsp;<\/p>\n<p>This concludes the interactive tutorial. <\/p>\n",
"type":"info",
"bubblestyle_d":"_default",
"b_width":150,
"b_height":40,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"bright_title_green",
"b_width_p":512,
"b_height_p":70,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.329549",
"y":"0.753628"}
,
"DocXY":{
"x":"0.329549",
"y":"0.753628"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":25,
"title":"Creating Purchase Requistions",
"audio":"",
"uid":"TS_2C7CD11F0F874750BC85ED92E7C12230",
"jumpable":true,
"visible":true,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_slide",
"time":0,
"duration":10,
"uid":"MAC_12A11B2357211F8C",
"src":"slide!SL_C342666F25D73690:",
"page_duration":-1,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":false,
"in_guided":false,
"in_pres":false,
"doc_enable":false,
"process_enable":false,
"doc_heading":false}
,{
"macro_template":"end_unit",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_2AD05AAB6857A1A7"}
]
}
]
}
